### ISSUE TITLE
nao use metodos magicos `on_objeto_signal`

### ISSUE THREAD

**Issue by tcanabrava** [igorpadua/kegen#5]
https://github.com/igorpadua/kegen/blob/b912b96b3d1a6da0c7226614a822d699c281d86d/mainwindow.cpp#L38

Se voce por acaso mudar o nome do elemento no .ui, o codigo vai compilar, mesmo com codigo quebrado. prefira sempre conexoes explicitas.

**Comment by igorpadua** [comment]
Tomaz tem alguma documentação de como faz essas conexões explicitas?

**Comment by tcanabrava** [comment]
Igual ao Connect que você usou acima pra o QProcess
